name: nogil bulider

on:
    workflow_dispatch:
    
jobs:      
    mambaforge:
        name: mambaforge (${{ matrix.os }}, Mambaforge, Python 3.9)
        runs-on: ${{ matrix.os }}-latest
        strategy:
            fail-fast: false
            matrix:
                os: ["Arch", "macOS", "windows"]
                # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
                include:
                -
                    os: Arch
                    miniforge-variant: Mambaforge
                - 
                    os: macos
                    miniforge-variant: Mambaforge
                - 
                    os: windows
                    miniforge-variant: Mambaforge

        steps:
            - 
                name: Checkout master
                uses: actions/checkout@v3
                with:
                    ref: main
        
            # 安装conda环境
            - 
                uses: conda-incubator/setup-miniconda@v2
                with:
                    # condarc-file: ${{ matrix.condarc-file }}
                    miniforge-variant: ${{ matrix.miniforge-variant }}
                    miniforge-version: ${{ matrix.miniforge-version }}
                    python-version: 3.9
                    # python-version: ${{ matrix.python-version }}
                    use-mamba: true

            - 
                # ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
                name: Fix windows
                if: matrix.os == 'windows'
                run: |
                    iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
                    scoop bucket add main
                    scoop install main/7zip
                    cd C:
                    curl -o sqlite-dll-win-x64-3450000.zip https://www.sqlite.org/2024/sqlite-dll-win-x64-3450000.zip
                    # expand -F:* sqlite-dll-win-x64-3450000.zip C:\Miniconda3\envs\test\DLLs
                    # expand -F:* sqlite-dll-win-x64-3450000.zip C:\Miniconda3\DLLs
                    7z.exe x -y -oC:\Miniconda3\DLLs C:\sqlite-dll-win-x64-3450000.zip
                    7z.exe x -y -oC:\Miniconda3\envs\test\DLLs C:\sqlite-dll-win-x64-3450000.zip
                    ls C:\Miniconda3\DLLs
                    ls C:\Miniconda3\envs\test\DLLs
            
            # - 
            #     name: Setup upterm session
            #     uses: lhotari/action-upterm@v1

            # -
            #     # configure: error: C compiler cannot create executables
            #     name: Fix MacOS
            #     if: matrix.os == 'macos'
            #     run: |
            #         xcode-select --install
            
            - name: Install Requirements
              run: |
                  mamba install conda-build anaconda-client
            
            - 
                name: Build the conda packages
                run: |
                    conda build . --no-anaconda-upload --output-folder ./pak

            - 
                name: publish-to-conda
                uses: fcakyon/conda-publish-action@v1.3
                with:
                    subdir: 'pak'
                    anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
                    platforms: ${{ matrix.os }}