name: nogil bulider

on:
    workflow_dispatch:
    
jobs:      
    mambaforge:
        name: mambaforge (${{ matrix.os }}, Mambaforge, Python 3.9)
        runs-on: ${{ matrix.os }}-latest
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu", "macOS", "windows"]
                # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
                include:
                -
                    os: ubuntu
                    miniforge-variant: Mambaforge
                - 
                    os: macos
                    miniforge-variant: Mambaforge
                - 
                    os: windows
                    miniforge-variant: Mambaforge

        steps:
            - 
                name: Checkout master
                uses: actions/checkout@v3
                with:
                    ref: main
        
            # 安装conda环境
            - 
                uses: conda-incubator/setup-miniconda@v2
                with:
                    # condarc-file: ${{ matrix.condarc-file }}
                    miniforge-variant: ${{ matrix.miniforge-variant }}
                    miniforge-version: ${{ matrix.miniforge-version }}
                    python-version: 3.9
                    # python-version: ${{ matrix.python-version }}
                    use-mamba: true
            
            - name: Install Requirements
              run: |
                  mamba install conda-build anaconda-client
            
            - 
                name: Build the conda packages
                run: |
                    conda build . --no-anaconda-upload --output-folder ./pak

            - 
                name: publish-to-conda
                uses: fcakyon/conda-publish-action@v1.3
                with:
                    subdir: 'pak'
                    anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
                    platforms: ${{ matrix.os }}