name: nogil bulider

on:
    workflow_dispatch:
    
jobs:      
    mambaforge:
        name: mambaforge (${{ matrix.os }}, Mambaforge, Python 3.9
        runs-on: ${{ matrix.os }}-latest
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu", "macOS", "windows"]
                # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
                include:
                -
                    os: ubuntu
                    miniforge-variant: Mambaforge
                - 
                    os: macos
                    miniforge-variant: Mambaforge
                - 
                    os: windows
                    miniforge-variant: Mambaforge

        steps:
            - 
                name: Checkout master
                uses: actions/checkout@v3
                with:
                    ref: main
        
            # 安装conda环境
            - 
                uses: conda-incubator/setup-miniconda@v2
                with:
                    # condarc-file: ${{ matrix.condarc-file }}
                    miniforge-variant: ${{ matrix.miniforge-variant }}
                    miniforge-version: ${{ matrix.miniforge-version }}
                    python-version: 3.9
                    # python-version: ${{ matrix.python-version }}
                    use-mamba: true
            
            - name: Install Requirements
              run: |
                  mamba install conda-build anaconda-client
            
            - 
                name: Build and upload the conda packages
                uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
                with:
                    meta_yaml_dir: ./recipe
                    # python-version: ${{ matrix.python-version }}
                    # python_version: 3.9
                    user: ${{ secrets.CONDA_USER }}
                    label: dev
                    token: ${{ secrets.ANACONDA_TOKEN }}
                    overwrite: true

      